schema_version: 1

context:
  name: uncertainty-toolbox
  version: "0.1.1"

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://github.com/${{ name }}/${{ name }}/archive/refs/tags/v${{ version }}.tar.gz
  sha256: 2d792cfae317621f06570e5f2afa5e74ab8fa79603fc5a00f079d276526119e4

build:
  number: 2
  noarch: python
  script: ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - python ${{ python_min }}.*
    - pip
    - flit-core
  run:
    - python >=${{ python_min }}
    - numpy >=1.19.0
    - scipy >=1.5.0
    - matplotlib-base >=3.2.2
    - scikit-learn >=0.23.1
    - shapely >=1.6.4.post2
    - tqdm >=4.54.0
    - pytest >=5.4.3
    - black >=19.10b0

tests:
  - python:
      imports:
        - uncertainty_toolbox
      pip_check: true
      python_version:
        - ${{ python_min }}
        - "*"

about:
  license: MIT
  license_file: LICENSE
  summary: A python toolbox for predictive uncertainty quantification, calibration, metrics, and visualization
  description: |
    Uncertainty Toolbox provides standard metrics to quantify and compare
    predictive uncertainty estimates, gives intuition for these metrics,
    produces visualizations of these metrics/uncertainties, and
    implements simple "re-calibration" procedures to improve these
    uncertainties. This toolbox currently focuses on regression tasks.
  homepage: https://uncertainty-toolbox.github.io/
  repository: https://github.com/uncertainty-toolbox/uncertainty-toolbox
  documentation: https://uncertainty-toolbox.github.io/docs/

extra:
  recipe-maintainers:
    - jan-janssen
